version: '3'

networks:
  backend:
  frontend:
    driver: bridge

volumes:
  preview:
  storage-framework:
  storage-logs:

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - storage-framework:/app/storage/framework:rw
      - storage-logs:/app/storage/logs:rw
      - ./src/.env:/app/.env:ro
    networks:
      - backend
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./src:/app:ro
    networks:
      - backend
      - frontend
  composer:
    image: composer:2.1
    restart: "no"
    command: composer install --ignore-platform-reqs --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --no-dev
    volumes:
      - ./src:/app
