version: "3"

services:
  frontend:
    image: "ghcr.io/thelfensdrfer/emma-goossens:main"
    platform: linux/amd64
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
